services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpass
    depends_on:
      - mongo

  api-server:
    build:
      context: C:/Projects/demo/api-server
      dockerfile: C:/Projects/demo/ApiServerDockerfile
    container_name: api-server
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb
    expose:
      - "5000"
    volumes:
      - C:/Projects/demo/api-server/:/app
    depends_on:
      - mongo

  client-server:
    build:
      context: C:/Projects/demo/client-server
      dockerfile: C:/Projects/demo/ClientServerDockerfile
    container_name: client-server
    ports:
      - "5173:5173"
    volumes:
      - C:/Projects/demo/client-server/:/app
    depends_on:
      - api-server

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client-server
      - api-server
      - mongo-express

volumes:
  mongo-data: